### PR TITLE
maint: build wheels for macos arm64 in Cirrus CI

### PR DESCRIPTION
**Pull request by oscarbenjamin**
This adds Cirrus CI configuration that can build macOS arm64 wheels.

Cirrus CI needs to be enabled on the repo before this will work.

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
@fredrik-johansson can you enable Cirrus CI on this repo?

The link is here:
https://github.com/marketplace/cirrus-ci

Only the "public repositories" (free) level is needed. After it asks for a name and address and some access to your github account to see your repos. It's possible to enable it only on one repo though.

**Comment by fredrik-johansson** [comment]
Cirrus CI seems to be installed now.

**Comment by oscarbenjamin** [comment]
Thanks. Looks like it's working. It should take about 15 minutes to produce the wheels.

**Comment by oscarbenjamin** [comment]
It's working. I've tested one of the wheels locally.

Next what is needed is to patch gap:
https://github.com/aleaxit/gmpy/issues/352#issuecomment-1360941902

I want to try to reproduce this issue first so that I can confirm the fix:
https://github.com/aleaxit/gmpy/issues/350

**Comment by oscarbenjamin** [comment]
> I want to try to reproduce this issue

Actually I'm really not sure how I would reproduce that because obviously I've compiled python_flint rather than gmpy. The equivalent code for python_flint doesn't have any problem but that doesn't really prove anything. I think it's clear that GMP needs to be patched though (various other environments apply this patch for macos arm64).

**Comment by oscarbenjamin** [comment]
I've added the patch for OSX arm64 and tested the wheel from Cirrus CI locally and it works.

**Comment by oscarbenjamin** [comment]
Okay, I think this is good to go.

**Pull request merged**
